name: Run Nonce Demo

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:  

jobs:
  run-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.29'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install repo
        run: |
            make install
            cd packages/contracts
            make setup

      - name: Run Nonce Demo
        env:
            PRIVATE_KEY_TEST: "0x5832c3fc8dced2c02fa5eca2e3c040e7637df37027c752bf40ec6b5b74991fb4"
            CONFIG: "TEST"
            BUNDLER_TEST: "https://bundler-staging.happy.tech"
            RPC_TEST: "https://happy-testnet-sepolia.rpc.caldera.xyz/http"
        run: | 
            cd packages/contracts    
            make nonce-demo
